name: Docker Test

on:
  workflow_dispatch:   # lo puedes lanzar manualmente desde GitHub Actions

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Docker login
        run: docker info

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-image:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-image:latest
