# This name will appear in the "Actions" tab of your GitHub repository.
name: Python CI/CD Pipeline

# This section defines the triggers for the workflow.
# It will run on every push to any branch and on any pull request.
on:
  push:
    branches: [ "**" ] # Runs on pushes to all branches
  pull_request:
    branches: [ "main" ] # Runs on pull requests targeting the main branch
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Docker login
        run: docker info

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-image:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-image:latest